### ISSUE TITLE
Seed data incorrect

### ISSUE THREAD

**Issue by shy-duck** [sarimabbas/project-winter-sound#5] opened 2019-11-19 19:03 UTC
"it has the right event information"
     I should find that it has the right title information. The title
     should be "BBQ for managers".

**Comment by sarimabbas** [comment] 2019-12-10 18:25
Duplicate of https://github.com/sarimabbas/project-winter-sound/issues/3, which was closed.

**Closed as completed by sarimabbas** 2019-12-10 18:25 UTC
